let nextUserId = 7;
let nextCourseId = 9;
let nextCategoryId = 7;

export const users = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'administrator',
    is_active: true,
    profile_photo: null,
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-08-20T10:30:00Z',
  },
  {
    id: 2,
    name: 'John Teacher',
    email: 'john@example.com',
    role: 'teacher',
    is_active: true,
    profile_photo: null,
    created_at: '2025-02-10T09:00:00Z',
    updated_at: '2025-07-15T14:00:00Z',
  },
  {
    id: 3,
    name: 'Jane Teacher',
    email: 'jane@example.com',
    role: 'teacher',
    is_active: true,
    profile_photo: null,
    created_at: '2025-03-05T10:00:00Z',
    updated_at: '2025-08-10T09:00:00Z',
  },
  {
    id: 4,
    name: 'Alice Student',
    email: 'alice@example.com',
    role: 'student',
    is_active: true,
    profile_photo: null,
    created_at: '2025-04-20T11:00:00Z',
    updated_at: '2025-08-01T16:00:00Z',
  },
  {
    id: 5,
    name: 'Bob Student',
    email: 'bob@example.com',
    role: 'student',
    is_active: false,
    profile_photo: null,
    created_at: '2025-05-12T12:00:00Z',
    updated_at: '2025-07-25T08:00:00Z',
  },
  {
    id: 6,
    name: 'Charlie Student',
    email: 'charlie@example.com',
    role: 'student',
    is_active: true,
    profile_photo: null,
    created_at: '2025-06-01T13:00:00Z',
    updated_at: '2025-08-18T11:00:00Z',
  },
];

export const categories = [
  {
    id: 1,
    slug: 'web-development',
    name: 'Web Development',
    description: 'HTML, CSS, JavaScript, and modern frameworks',
    courses_count: 3,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2025-08-15T10:00:00Z',
  },
  {
    id: 2,
    slug: 'data-science',
    name: 'Data Science',
    description: 'Python, machine learning, and data analysis',
    courses_count: 2,
    created_at: '2025-01-12T08:00:00Z',
    updated_at: '2025-08-10T10:00:00Z',
  },
  {
    id: 3,
    slug: 'mobile-development',
    name: 'Mobile Development',
    description: 'React Native, Flutter, and native app development',
    courses_count: 2,
    created_at: '2025-02-01T08:00:00Z',
    updated_at: '2025-08-05T10:00:00Z',
  },
  {
    id: 4,
    slug: 'devops',
    name: 'DevOps',
    description: 'CI/CD, Docker, Kubernetes, and cloud deployment',
    courses_count: 1,
    created_at: '2025-03-01T08:00:00Z',
    updated_at: '2025-07-20T10:00:00Z',
  },
  {
    id: 5,
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    description: 'User interface and user experience design principles',
    courses_count: 1,
    created_at: '2025-03-15T08:00:00Z',
    updated_at: '2025-08-12T10:00:00Z',
  },
  {
    id: 6,
    slug: 'cybersecurity',
    name: 'Cybersecurity',
    description: 'Network security, ethical hacking, and compliance',
    courses_count: 0,
    created_at: '2025-04-01T08:00:00Z',
    updated_at: '2025-04-01T08:00:00Z',
  },
];

export const courses = [
  {
    id: 1,
    slug: 'intro-to-html-css',
    title: 'Introduction to HTML & CSS',
    description: 'Learn the fundamentals of web markup and styling. Build your first web page from scratch with semantic HTML and modern CSS layout techniques.',
    category: { id: 1, name: 'Web Development' },
    difficulty_level: 'beginner',
    duration: '3 hours',
    status: 'published',
    thumbnail: null,
    teacher: { id: 2, name: 'John Teacher' },
    created_at: '2025-02-15T09:00:00Z',
    updated_at: '2025-08-01T14:00:00Z',
  },
  {
    id: 2,
    slug: 'javascript-fundamentals',
    title: 'JavaScript Fundamentals',
    description: 'Master the core concepts of JavaScript including variables, functions, loops, DOM manipulation, and async programming.',
    category: { id: 1, name: 'Web Development' },
    difficulty_level: 'beginner',
    duration: '5 hours',
    status: 'published',
    thumbnail: null,
    teacher: { id: 2, name: 'John Teacher' },
    created_at: '2025-03-01T10:00:00Z',
    updated_at: '2025-08-05T11:00:00Z',
  },
  {
    id: 3,
    slug: 'react-for-beginners',
    title: 'React for Beginners',
    description: 'Get started with React.js. Learn component-based architecture, hooks, state management, and build interactive UIs.',
    category: { id: 1, name: 'Web Development' },
    difficulty_level: 'intermediate',
    duration: '8 hours',
    status: 'draft',
    thumbnail: null,
    teacher: { id: 3, name: 'Jane Teacher' },
    created_at: '2025-04-10T11:00:00Z',
    updated_at: '2025-08-10T09:00:00Z',
  },
  {
    id: 4,
    slug: 'python-for-data-science',
    title: 'Python for Data Science',
    description: 'Learn Python programming with a focus on data analysis. Covers NumPy, Pandas, Matplotlib, and Jupyter notebooks.',
    category: { id: 2, name: 'Data Science' },
    difficulty_level: 'beginner',
    duration: '6 hours',
    status: 'published',
    thumbnail: null,
    teacher: { id: 3, name: 'Jane Teacher' },
    created_at: '2025-03-20T09:00:00Z',
    updated_at: '2025-07-25T15:00:00Z',
  },
  {
    id: 5,
    slug: 'machine-learning-basics',
    title: 'Machine Learning Basics',
    description: 'Introduction to machine learning concepts. Understand supervised and unsupervised learning, model evaluation, and real-world applications.',
    category: { id: 2, name: 'Data Science' },
    difficulty_level: 'intermediate',
    duration: '10 hours',
    status: 'draft',
    thumbnail: null,
    teacher: { id: 2, name: 'John Teacher' },
    created_at: '2025-05-01T10:00:00Z',
    updated_at: '2025-08-15T12:00:00Z',
  },
  {
    id: 6,
    slug: 'flutter-app-development',
    title: 'Flutter App Development',
    description: 'Build cross-platform mobile apps with Flutter and Dart. Create beautiful, performant apps for iOS and Android from a single codebase.',
    category: { id: 3, name: 'Mobile Development' },
    difficulty_level: 'intermediate',
    duration: '12 hours',
    status: 'published',
    thumbnail: null,
    teacher: { id: 2, name: 'John Teacher' },
    created_at: '2025-04-25T08:00:00Z',
    updated_at: '2025-08-20T10:00:00Z',
  },
  {
    id: 7,
    slug: 'react-native-essentials',
    title: 'React Native Essentials',
    description: 'Create mobile apps using React and JavaScript. Learn navigation, state management, and native device features.',
    category: { id: 3, name: 'Mobile Development' },
    difficulty_level: 'intermediate',
    duration: '9 hours',
    status: 'archived',
    thumbnail: null,
    teacher: { id: 3, name: 'Jane Teacher' },
    created_at: '2025-05-15T11:00:00Z',
    updated_at: '2025-07-30T14:00:00Z',
  },
  {
    id: 8,
    slug: 'docker-kubernetes-101',
    title: 'Docker & Kubernetes 101',
    description: 'Containerize applications with Docker and orchestrate them with Kubernetes. Deploy scalable, resilient microservices.',
    category: { id: 4, name: 'DevOps' },
    difficulty_level: 'advanced',
    duration: '7 hours',
    status: 'published',
    thumbnail: null,
    teacher: { id: 2, name: 'John Teacher' },
    created_at: '2025-06-01T09:00:00Z',
    updated_at: '2025-08-18T11:00:00Z',
  },
];

export const mockAdmin = {
  id: 1,
  name: 'Admin User',
  email: 'admin@example.com',
  role: 'administrator',
  is_active: true,
  profile_photo: null,
  created_at: '2025-01-15T08:00:00Z',
  updated_at: '2025-08-20T10:30:00Z',
};

export function getNextUserId() {
  return nextUserId++;
}

export function getNextCourseId() {
  return nextCourseId++;
}

export function getNextCategoryId() {
  return nextCategoryId++;
}
